### ISSUE TITLE
SPLAT('') returns division by zero

### ISSUE THREAD

**Issue by andymeneely** [meyersbs/SPLAT#32]
Here's my terminal output:
```
>python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from splat.SPLAT import SPLAT
>>> SPLAT('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\andy.SE\AppData\Local\Programs\Python\Python37\lib\site-packages\splat\SPLAT.py", line 104, in __init__
    self.__ttr = Util.type_token_ratio(self.__types, self.__tokens)
  File "C:\Users\andy.SE\AppData\Local\Programs\Python\Python37\lib\site-packages\splat\Util.py", line 67, in type_token_ratio
    return round(float(len(types)) / float(len(tokens)), 4)
ZeroDivisionError: float division by zero
>>>
```

Seems like this should be NaN or something else.

**Comment by meyersbs** [comment]
_**Facepalm**_ -- I never thought to test SPLAT on an empty string; SPLAT analyzes natural language, which definitely doesn't include empty strings. I was a bad developer when I started writing SPLAT, and while that's no excuse, that _is_ why SPLAT is getting a major rewrite from the ground up.
