### ISSUE TITLE
SPLAT() on a long string fails on windows - long filename

### ISSUE THREAD

**Issue by andymeneely** [meyersbs/SPLAT#33]
I got this stacktrace:

```
Running git command:
  git log --pretty="%B" -- ui/base/clipboard/clipboard_aurax11.cc
  in ../chromium-vulnerabilities/tmp/src
Traceback (most recent call last):
  File "generate\gitlog\blather.py", line 102, in <module>
    generate_from_chromium()
  File "generate\gitlog\blather.py", line 91, in generate_from_chromium
    output_file = 'data/blather/chromium-blather.csv')
  File "generate\gitlog\blather.py", line 67, in generate_from_repo
    writer.writerow([file] + doNLP(git_result, num_commits))
  File "generate\gitlog\blather.py", line 17, in doNLP
    curr_splat = SPLAT(text)
  File "C:\Users\andy.SE\AppData\Local\Programs\Python\Python37\lib\site-packages\splat\SPLAT.py", line 67, in __init__
    if os.path.isfile(text):
  File "C:\Users\andy.SE\AppData\Local\Programs\Python\Python37\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
ValueError: stat: path too long for Windows
```
...even though it was never intended that this was a filename. I'm thinking this is probably not the approach you want.

**Comment by meyersbs** [comment]
I've run into SPLAT breaking when an external script passes it a string containing a filename before. This is a little different because it appears to be Windows-specific. I've always been open about the fact that I don't test my code on Windows, but I'll definitely keep this in mind in my rewrite of [SPLAT](https://github.com/meyersbs/SPLAT/tree/splat2).

**Comment by andymeneely** [comment]
Yeah but I don't think that it's a good idea to mix filenames and input texts into the same input. Just take in a string and don't check if it's a file in the first place. I was surprised it assumed my input might be a file anyway.

SPLAT("README") - is that a file or a word?

**Comment by meyersbs** [comment]
Fair point. The intent was to have SPLAT check the CWD for a file called `README` and if it exists, get the text from there. It's a side effect of trying to make SPLAT work as a library and a CLI before I actually knew anything about how Python actually works.
